### ISSUE TITLE
Yoast Meta Box Not Working

### ISSUE THREAD

**Issue by sanjayblr** [Yoast/yoast-acf-analysis#86]
Hi,

I am using Yoast Premium and ACF, the analysis tool is not working and only partially visible. I deactivated ACF and the Meta-Analysis Box started working. I installed the ACF Content Analysis for Yoast SEO to try and fix the issue but this not correct the problem.

I am using the SmartBox theme which I know is very old, plan to update the website in the next 3 months but I would like to the fix the issue with the Meta-Analysis box as soon as I can so would appreciate any help or advice to fix.

Thanks
Sanjay

**Comment by kraftner** [comment]
So your problem appears If you use Yoast SEO and ACF, while not having ACF Content Analysis for Yoast SEO activated?

**Comment by sanjayblr** [comment]
Yes, when I deactivated ACF the content analysis worked fine. Unfortunately, my homepage is built using ACF's so I cannot leave the plugin deactivated. Any help/advice would be greatly appreciated.

**Comment by kraftner** [comment]
Sorry if I wasn't clear, but my question actually was if this state causes the problem as well:

- [X] Yoast SEO (active)
- [X] Advanced Custom fields (active)
- [ ] ACF Content Analysis for Yoast SEO (inactive/not installed)

---

Because to me your description sounds as if you're having a problem with just the combination of Yoast SEO and ACF and tried to fix it by installing ACF Content Analysis for Yoast SEO. If that is the case something is wrong with Yoast SEO itself as this plugin (ACF Content Analysis for Yoast SEO) is just there to enhance compatibility but not to fix an otherwise broken compatibility.

Also could you please add the exact version of WordPress and all Plugins you have installed and active?

**Comment by kraftner** [comment]
Can you try upgrading to `2.0.1` and report back. I suspect this should be fixed.

**Comment by TLanetteRose** [comment]
I had the same issue and I finally found the problem. It was the plugin Black Studio TinyMCE Widget. Once I deleted it, the meta description box and analytics came back. I have the Verbosa theme.
